/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import static forms.login.nombreUsuario;
import java.awt.Image;
import proybiblioteca.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.Timestamp;
import java.time.LocalDate;
import javax.swing.ImageIcon;

/**
 *
 * @author esleyder-torres
 */
public class formAgregarLibro extends javax.swing.JFrame {

    private byte[] portadaBLOB = null;
    private final String usuarioIngreso = nombreUsuario.toUpperCase();

    public formAgregarLibro() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAnioAgregar = new javax.swing.JTextField();
        txtTituloAgregar = new javax.swing.JTextField();
        txtISBNAgregar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtGeneroAgregar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadAgregar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAutorAgregar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIdiomaAgregar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEditorialAgregar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnGuardarLibro = new javax.swing.JButton();
        btnCancelarAgregar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRatingAgregar = new javax.swing.JTextField();
        lblPortadaAgregar = new javax.swing.JLabel();
        btnCargarPortada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel7.setText("Editorial:");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel8.setText("Idioma:");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtAnioAgregar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtAnioAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioAgregarActionPerformed(evt);
            }
        });

        txtTituloAgregar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtTituloAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloAgregarActionPerformed(evt);
            }
        });

        txtISBNAgregar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtISBNAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNAgregarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Título:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtGeneroAgregar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtGeneroAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroAgregarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("ISBN:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtCantidadAgregar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtCantidadAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadAgregarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Género:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtAutorAgregar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtAutorAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorAgregarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setText("Cantidad:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtIdiomaAgregar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtIdiomaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdiomaAgregarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel5.setText("Autor:");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtEditorialAgregar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtEditorialAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditorialAgregarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel6.setText("Año:");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnGuardarLibro.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        btnGuardarLibro.setText("AGREGAR");
        btnGuardarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLibroActionPerformed(evt);
            }
        });

        btnCancelarAgregar.setText("CANCELAR");
        btnCancelarAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAgregarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel9.setText("Rating:");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel10.setText("Portada:");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtRatingAgregar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtRatingAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRatingAgregarActionPerformed(evt);
            }
        });

        lblPortadaAgregar.setText("                            PORTADA");
        lblPortadaAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCargarPortada.setText("Cargar imagen");
        btnCargarPortada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarPortadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRatingAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCargarPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTituloAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtISBNAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGeneroAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAutorAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdiomaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEditorialAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(90, 90, 90)
                .addComponent(lblPortadaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(359, 359, 359))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarAgregar)
                .addGap(387, 387, 387))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTituloAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtISBNAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtGeneroAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCantidadAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtAutorAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtAnioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtEditorialAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtIdiomaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtRatingAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(btnCargarPortada))
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblPortadaAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61)))
                .addComponent(btnGuardarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnCancelarAgregar)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnioAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioAgregarActionPerformed

    private void txtTituloAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloAgregarActionPerformed

    private void txtISBNAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNAgregarActionPerformed

    private void txtGeneroAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroAgregarActionPerformed

    private void txtCantidadAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadAgregarActionPerformed

    private void txtAutorAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorAgregarActionPerformed

    private void txtIdiomaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdiomaAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdiomaAgregarActionPerformed

    private void txtEditorialAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditorialAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditorialAgregarActionPerformed

    private void btnGuardarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLibroActionPerformed
 Conexion cc = new Conexion();
Connection cn = cc.conectar();
String sql = "INSERT INTO Libros (Titulo, ISBN, genero, cantidad, Autor, anio_publicacion, editorial, idioma, Rating_promedio, Portada, Fecha_ingreso, usuario_ingreso) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

try (PreparedStatement pst = cn.prepareStatement(sql)) {

    pst.setString(1, txtTituloAgregar.getText().trim());
    pst.setString(2, txtISBNAgregar.getText().trim());
    pst.setString(3, txtGeneroAgregar.getText().trim());


    try {
        int cantidad = Integer.parseInt(txtCantidadAgregar.getText().trim());
        pst.setInt(4, cantidad);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La cantidad debe ser un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    pst.setString(5, txtAutorAgregar.getText().trim());
    pst.setString(6, txtAnioAgregar.getText().trim());
    pst.setString(7, txtEditorialAgregar.getText().trim());
    pst.setString(8, txtIdiomaAgregar.getText().trim());


    String ratingTexto = txtRatingAgregar.getText().trim();
    if (!ratingTexto.isEmpty()) {
        try {
            double rating = Double.parseDouble(ratingTexto);
            pst.setDouble(9, rating);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El rating debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } else {
        pst.setNull(9, java.sql.Types.DOUBLE);
    }


    pst.setBytes(10, portadaBLOB);

 LocalDate fechaActual = LocalDate.now();
java.sql.Date fechaSql = java.sql.Date.valueOf(fechaActual);
pst.setDate(11, fechaSql);

    pst.setString(12, usuarioIngreso);
    int resultado = pst.executeUpdate();
    if (resultado > 0) {
        JOptionPane.showMessageDialog(this, "Libro agregado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        limpiarCamposAgregar();
        portadaBLOB = null;
        lblPortadaAgregar.setIcon(null);
        lblPortadaAgregar.setText("Portada");
    } else {
        JOptionPane.showMessageDialog(this, "Error al agregar el libro.", "Error", JOptionPane.ERROR_MESSAGE);
    }

} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Error con la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
} finally {
    try {
        if (cn != null) {
            cn.close();
        }
    } catch (SQLException ex) {
        System.err.println("Error al cerrar la conexión: " + ex.getMessage());
    }
}

    }//GEN-LAST:event_btnGuardarLibroActionPerformed

    private void btnCancelarAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAgregarActionPerformed
        this.dispose(); // Cierra el formulario
    }

    private void limpiarCamposAgregar() {
        txtTituloAgregar.setText("");
        txtISBNAgregar.setText("");
        txtGeneroAgregar.setText("");
        txtCantidadAgregar.setText("");
        txtAutorAgregar.setText("");
        txtAnioAgregar.setText("");
        txtEditorialAgregar.setText("");
        txtIdiomaAgregar.setText("");
        txtRatingAgregar.setText("");     // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarAgregarActionPerformed

    private void txtRatingAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRatingAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRatingAgregarActionPerformed

    private void btnCargarPortadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarPortadaActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de imagen", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(filtro);

        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            try (FileInputStream fis = new FileInputStream(archivoSeleccionado)) {
                portadaBLOB = fis.readAllBytes();
                // Mostrar una vista previa de la imagen (opcional)
                ImageIcon icon = new ImageIcon(portadaBLOB);
                Image scaledImage = icon.getImage().getScaledInstance(lblPortadaAgregar.getWidth(), lblPortadaAgregar.getHeight(), Image.SCALE_SMOOTH);
                lblPortadaAgregar.setIcon(new ImageIcon(scaledImage));
                lblPortadaAgregar.setText("");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al cargar la imagen.", "Error", JOptionPane.ERROR_MESSAGE);
                portadaBLOB = null;
                lblPortadaAgregar.setIcon(null);
                lblPortadaAgregar.setText("Error");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarPortadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formAgregarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formAgregarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formAgregarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formAgregarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formAgregarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarAgregar;
    private javax.swing.JButton btnCargarPortada;
    private javax.swing.JButton btnGuardarLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblPortadaAgregar;
    private javax.swing.JTextField txtAnioAgregar;
    private javax.swing.JTextField txtAutorAgregar;
    private javax.swing.JTextField txtCantidadAgregar;
    private javax.swing.JTextField txtEditorialAgregar;
    private javax.swing.JTextField txtGeneroAgregar;
    private javax.swing.JTextField txtISBNAgregar;
    private javax.swing.JTextField txtIdiomaAgregar;
    private javax.swing.JTextField txtRatingAgregar;
    private javax.swing.JTextField txtTituloAgregar;
    // End of variables declaration//GEN-END:variables
}
